name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  provider: ^6.1.5
  firebase_ui_auth: ^1.17.0
  flutter_arc_text: ^0.6.0
  google_generative_ai: ^0.4.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_gen: ^5.10.0
  webview_flutter: ^4.13.0
  wave_progress_indicator: ^0.0.1
  flutter_polls: ^0.1.6
  shared_preferences: ^2.5.3
  rxdart: ^0.28.0
  google_fonts: ^6.3.1
  file_picker: ^10.3.2
  go_router: ^16.2.4
  dotted_border: ^3.1.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_data_connect: ^0.1.5+4



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/score/
    - assets/test/
    - assets/sound/timer_finish.mp3
    - assets/sound/timer_warning.mp3
